databases:
  - name: kmtestuser-crud_sample
    databaseName: crud_sample_production
    user: crud_sample
    region: singapore

services:
  - type: web
    name: crud_sample
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kmtestuser-crud_sample
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false